version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ../app:/app:rw
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:8.0-fpm
    volumes:
      - ../app:/app:rw